services:
  youtools-frontend:
    container_name: youtools-frontend
    image: youtools-frontend
    ports:
      - "8080:8080"
    environment:
      - NGINX_ENABLE_ABSOLUTE_REDIRECT=no
    restart: always
