services:
  youtools-frontend:
    container_name: youtools-frontend
    image: samirul08/youtools-frontend
    env_file:
      - ".env"
    ports:
      - "8080:8080"
    environment:
      - NGINX_ENABLE_ABSOLUTE_REDIRECT=no
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 300M
